apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-tfyvtbdx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-tfyvtbdx:33fb8427f90999953b5cfeec5be303b81f94103c@sha256:b5cc0051d8ee59beda6235973edd8ced95b1a62d653329310b5e17983eafa527
          name: container-image
